"""empty message

Revision ID: d207405681a2
Revises: 
Create Date: 2022-10-26 22:01:51.419026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd207405681a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('forward_id', sa.Integer(), nullable=True),
    sa.Column('back_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['back_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['forward_id'], ['questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
