# Generated by Django 3.0.4 on 2020-09-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='back',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='forward',
            field=models.IntegerField(null=True),
        ),
    ]
