# Generated by Django 3.0.4 on 2020-09-12 16:16

import Question.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_auto_20200912_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='back',
            field=models.IntegerField(null=True, validators=[Question.models.validate_id]),
        ),
        migrations.AlterField(
            model_name='question',
            name='forward',
            field=models.IntegerField(null=True, validators=[Question.models.validate_id]),
        ),
    ]
