# Generated by Django 3.0.4 on 2020-09-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0004_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(),
        ),
    ]
